### ISSUE TITLE
how to implement in java

### ISSUE THREAD

**Issue by ThreeMinutesFix** [ozgurg/ToggleIconView#20]
what is code to implement in java?

**Comment by ozgurg** [comment]
Hi. The setup and layout usage are the same.

In your layout you can find the icon by its ID and use it like any other view.

```xml
<og.android.lib.toggleiconview.rounded.PlayPause
    android:id="@+id/playPause"
    android:layout_width="24dp"
    android:layout_height="24dp" />
```

```java
ToggleIconView toggleIconView = (ToggleIconView) findViewById(R.id.playPause);

toggleIconView.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        toggleIconView.toggle();
    }
});

toggleIconView.setOnCheckedChangeListener(new Function2<ToggleIconView, Boolean, Unit>() {
    @Override
    public Unit invoke(ToggleIconView view, Boolean isChecked) {
        Toast.makeText(getApplicationContext(), isChecked.toString(), Toast.LENGTH_SHORT).show();
        return null;
    }
});

// toggleIconView.toggle();
// toggleIconView.setChecked(...);
// toggleIconView.isChecked();
// toggleIconView.setCheckedContentDescription(...);
// toggleIconView.getCheckedContentDescription();
// toggleIconView.setCheckedTooltipText(...);
// toggleIconView.getCheckedTooltipText()
```

But if I can create an interface for onCheckedChangeListener, the code will make more sense when used with Java. I'll look into this.

**Comment by ozgurg** [comment]
> Hi. The setup and layout usage are the same.
> 
> In your layout you can find the icon by its ID and use it like any other view.
> 
> ```
> <og.android.lib.toggleiconview.rounded.PlayPause
>     android:id="@+id/playPause"
>     android:layout_width="24dp"
>     android:layout_height="24dp" />
> ```
> 
> ```java
> ToggleIconView toggleIconView = (ToggleIconView) findViewById(R.id.playPause);
> 
> toggleIconView.setOnClickListener(new View.OnClickListener() {
>     @Override
>     public void onClick(View view) {
>         toggleIconView.toggle();
>     }
> });
> 
> toggleIconView.setOnCheckedChangeListener(new Function2<ToggleIconView, Boolean, Unit>() {
>     @Override
>     public Unit invoke(ToggleIconView view, Boolean isChecked) {
>         Toast.makeText(getApplicationContext(), isChecked.toString(), Toast.LENGTH_SHORT).show();
>         return null;
>     }
> });
> 
> // toggleIconView.toggle();
> // toggleIconView.setChecked(...);
> // toggleIconView.isChecked();
> // toggleIconView.setCheckedContentDescription(...);
> // toggleIconView.getCheckedContentDescription();
> // toggleIconView.setCheckedTooltipText(...);
> // toggleIconView.getCheckedTooltipText()
> ```
> 
> But if I can create an interface for onCheckedChangeListener, the code will make more sense when used with Java. I'll look into this.

Hi again, I updated the library. Now you can use the listener like this:

```java
toggleIconView.setOnCheckedChangeListener(new ToggleIconView.OnCheckedChangeListener() {
    @Override
    public void onCheckedChanged(@NonNull ToggleIconView view, boolean isChecked) {
        Toast.makeText(getApplicationContext(), isChecked.toString(), Toast.LENGTH_SHORT).show();
    }
});
```

**Comment by ThreeMinutesFix** [comment]
thankyou somuch.thankyou for creating this amazing lib i will implement and tell you the result on my app

**Comment by ThreeMinutesFix** [comment]
![worked](https://github.com/ozgurg/ToggleIconView/assets/103521732/7e0ade70-9002-4fc1-b4f3-6254071513de)
your implementation worked perfectly :)
video preview: https://res.cloudinary.com/djdle8unh/video/upload/v1687506760/video_2023-06-23_13-22-21_ulvcai.mp4
in xml icon was not displayed so i added it manaully.

`        <og.android.lib.toggleiconview.rounded.PlayPause
            android:id="@+id/playPause"
            android:layout_width="84dp"
            android:src="@drawable/rounded_play_to_pause"
            android:tint="@color/white"
            android:layout_height="84dp" />`
Thanks again
